# Generated by Django 6.0.6 on 2026-06-27

from secrets import randbelow

from django.db import migrations, models
from django.utils.text import slugify


def generate_handle_base(name, email):
    value = slugify(name or email.split('@')[0]).replace('-', '')
    return value or 'user'


def populate_user_handles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    existing_handles = set(
        User.objects.exclude(handle__isnull=True)
        .exclude(handle='')
        .values_list('handle', flat=True)
    )

    for user in User.objects.filter(handle__isnull=True):
        base_handle = generate_handle_base(user.name, user.email)

        while True:
            handle = f'{base_handle}{randbelow(9000) + 1000}'

            if handle not in existing_handles:
                break

        user.handle = handle
        user.save(update_fields=['handle'])
        existing_handles.add(handle)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.RunPython(populate_user_handles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=180, unique=True),
        ),
    ]
