# Generated by Django 6.0.6 on 2026-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_handle_on_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
