# Generated by Django 6.0.6 on 2026-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofilechangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
